name: Go Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.24'  # Specify the Go version

      - name: Build
        run: |
          GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || 'windows' }}
          GOARCH=amd64
          go build -o myapp-${{ matrix.os }} main.go  # Adjust the output name as needed

      - name: Upload Release Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: myapp-${{ matrix.os }}
          path: myapp-${{ matrix.os }}